In [1]:
import numpy as np

In [182]:
a=[1,2,4,6,7,8,9,0,12,3]
arra= np.array(a)
print(arra,type(arra))


[ 1  2  4  6  7  8  9  0 12  3] <class 'numpy.ndarray'>


In [183]:
z=np.array([a,a])

In [185]:
print(z.size)
print(arra.size)
print(len(z),len(arra))
# gives total number of elements present in array

20
10
2 10


In [195]:
print(z.ndim)
print(arra.ndim)
# gives dimension
# 2d is 2, 1d is 1

2
1


In [224]:
print(z.shape)
print(arra.shape)

# gives z>> 2 row, 10 col
# gives arra>> 10 row, 1col

(2, 10)
(10,)


In [225]:
b={1,2,3,4}
bb=np.array(b)
print(bb,type(bb))
bb.ndim

{1, 2, 3, 4} <class 'numpy.ndarray'>


0

In [226]:
b=(1,2,3,4)
bb=np.array(b)
print(bb,type(bb))
bb.ndim

[1 2 3 4] <class 'numpy.ndarray'>


1

In [227]:
b={1:12,2:22,3:33,4:44}
bb=np.array(b)
print(bb,type(bb))
print(bb.ndim,bb.shape)
# print(arra.ndim)

{1: 12, 2: 22, 3: 33, 4: 44} <class 'numpy.ndarray'>
0 ()


In [228]:
b={1:12,2:22,3:33,4:44}
bb=np.array(b)
print(bb,type(bb))
bb.ndim

{1: 12, 2: 22, 3: 33, 4: 44} <class 'numpy.ndarray'>


0

In [229]:
b=[1,2,3,4]
bb=np.array(b)
print(bb,type(bb))
bb.size
bb.shape
bb.ndim

[1 2 3 4] <class 'numpy.ndarray'>


1

In [230]:
# do not use () for using numpy functions
# gives the 
arra.size

10

In [231]:
# shape-----(row,col)
arra.shape

(10,)

In [232]:
# gives the dim of the given array
arra.ndim

1

* SCALAR-- 0D
* vector--- 1D
* (row,col)---- 2D

In [239]:
[i for i in range(1,19)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [233]:
np.arange(1,19)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [11]:
# is a range function in NUmpy

array=np.arange(8)
array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [221]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [223]:
10/0.1


100.0

In [240]:
np.linspace(1,10,100)
# np.linspace(start,stop,number of samples)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

#### Creates equal div values given range

In [14]:
array=np.linspace(1,100,10)
array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [15]:
array=np.linspace(0,10,4)
array

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [16]:
array.ndim

1

In [7]:
np.zeros((2,3),np.int64)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [9]:
np.zeros((3,2),dtype=np.float64)


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### gives Zero elements in matrixof (nXm)

In [266]:
np.zeros((3,4),np.int8)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

#### Empty array give random matrix elements

In [360]:
e= np.empty((2,3),np.int8)
e

array([[-80, 101, 114],
       [101, 110,  99]], dtype=int8)

### Ones matrix

In [361]:
np.ones((3,4),np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

# identity matrix always in (nxn)

np.eye(4)

In [362]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### full matrix gives (nxm) matrix

In [363]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [364]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [365]:
np.zeros((3,4),[('x','i4'),('y','i4')])

array([[(0, 0), (0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0), (0, 0)]],
      dtype=[('x', '<i4'), ('y', '<i4')])

In [366]:
np.ones((3,4),[('x','i4'),('y','i4')])

array([[(1, 1), (1, 1), (1, 1), (1, 1)],
       [(1, 1), (1, 1), (1, 1), (1, 1)],
       [(1, 1), (1, 1), (1, 1), (1, 1)]],
      dtype=[('x', '<i4'), ('y', '<i4')])

In [367]:
np.full((2,2),[('x','i4'),('y','i4')])

array([['x', 'i4'],
       ['y', 'i4']], dtype='<U2')

In [368]:
f=np.full((3,3),[('a',1,2),('b',2,3),('c',3,4)])
f

array([['a', '1', '2'],
       ['b', '2', '3'],
       ['c', '3', '4']], dtype='<U11')

In [393]:
import random
import numpy as np
np.random.randint(1,9)

6

In [14]:
f'0.%2snp.random.rand(4,)'

'0.%2snp.random.rand(4,)'

In [426]:
np.full((3,3),[(1,"o",3),(1,'f',3),(1,2,3)])
np.full((3,4),[np.random.randint(1,99)])

array([[70, 70, 70, 70],
       [70, 70, 70, 70],
       [70, 70, 70, 70]])

In [394]:
z=np.full((3,3),(3,4,5))
z

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [395]:
z.T

array([[3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

### Convert any dim matrix into 1D matrix


In [33]:
z.flatten()


array([3, 4, 5, 3, 4, 5, 3, 4, 5])

In [34]:
f1=f.flatten()
f1.ndim

1

In [428]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
a=np.arange(6).reshape(2,3)
f1=z.flat
for item in f1:
    print(item)

3
4
5
3
4
5
3
4
5


In [430]:
q=np.arange(6).reshape(2,3)
[i for i in q.flat]
q

array([[0, 1, 2],
       [3, 4, 5]])

In [441]:
np.array([i for i in q.flat])

array([0, 1, 2, 3, 4, 5])

In [442]:
for i in z:
    print(i)

[3 4 5]
[3 4 5]
[3 4 5]


In [443]:
s=z.flatten()
# for i in s:
#     print(i)

s


array([3, 4, 5, 3, 4, 5, 3, 4, 5])

### to print matrix using array

In [444]:
a=np.array([[1,4],[4,8]])
a

array([[1, 4],
       [4, 8]])

In [445]:
np.array([[1,2],[2,3]])

array([[1, 2],
       [2, 3]])

In [447]:
b= np.array([[1,4],[4,8],[3,5]])
b.shape

(3, 2)

In [448]:
np.full((3,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [449]:
x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [452]:
x1=x.sum()
x2= x.sum(axis=0)
x3=x.mean()
np.mean(x)
np.log(x)


C:\Users\KIRAN Sonkamble\AppData\Local\Temp\ipykernel_12528\2366921796.py:5: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154]])

In [45]:
# Tells the shape of the matrix
x.shape

(3, 3)

In [456]:
# np function
np.mean(x)
# built in 
x.mean()

4.0

### indxing and slicing

In [459]:
s=np.array([1,2,0,4,6,7,12,88,2])
s

array([ 1,  2,  0,  4,  6,  7, 12, 88,  2])

In [460]:
s[2]

0

In [467]:
s[-4]
s[-4:-5:-1]

array([7])

In [469]:
s2

array([[ 1,  2,  0],
       [ 4,  6,  7],
       [12, 88,  2]])

In [477]:
s2=np.array([1,2,0,4,6,7,12,88,2]).reshape(3,3)
s2[0:,2]
s2[0:1:2]

array([[1, 2, 0]])

In [50]:
s1=[1,2,0,4,6,7,88,2]
s1[-1]

2

In [51]:
s[0]

1

In [52]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
x[0]       #row
x[1]      #row

array([3, 4, 5])

In [54]:
x[:,0]      #Column
# x[:,1]      #Column

array([0, 3, 6])

In [55]:
# [4,5]

x[1,1:]

array([4, 5])

In [56]:
# [6,7]
x[2,:2]

array([6, 7])

In [57]:
# [1,2] and [4,5]

x[:2,1:]

array([[1, 2],
       [4, 5]])

In [58]:
# [3,5]
x[1,:3:2]

array([3, 5])

In [59]:
x[::2]

array([[0, 1, 2],
       [6, 7, 8]])

In [60]:
x[:,::2]

array([[0, 2],
       [3, 5],
       [6, 8]])

In [61]:

x[::2,::2]
# x

array([[0, 2],
       [6, 8]])

In [62]:
# [1,7]
x[::2,1:2]

array([[1],
       [7]])

In [63]:
np.split(x,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
z=np.arange(25)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
np.split(z,[3,7,13])

[array([0, 1, 2]),
 array([3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12]),
 array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])]

In [66]:
np.split(z,[3,7,33])


[array([0, 1, 2]),
 array([3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24]),
 array([], dtype=int32)]

In [67]:
np.split(z,[1,6,22,28])

[array([0]),
 array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]),
 array([22, 23, 24]),
 array([], dtype=int32)]

In [68]:
np.split(x,[3,6],axis=1)

[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([], shape=(3, 0), dtype=int32),
 array([], shape=(3, 0), dtype=int32)]

In [69]:
# Other way to split it is hsplit and vsplit

np.hsplit(z,5)



# vsplit works with on;y 2d array
# np.vsplit(z,5)

np.vsplit(x,[2,4,6])



[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

### scalar stack or Concatination

In [70]:
np.concatenate((z,z))
               

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24,  0,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [71]:

np.concatenate((x,x))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
np.hstack((z,z))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24,  0,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [73]:
np.vstack((z,z))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [74]:
np.hstack((z,z)).shape
np.vstack((z,z)).shape

(2, 25)

In [75]:
np.hstack((x,x))
np.hstack((x,x)).shape

(3, 6)

In [76]:
np.vstack((x,x))
np.vstack((x,x)).shape

(6, 3)